name: 'Yarn upgrade'
description: 'Runs a yarn upgrade'
inputs:
  working-dir:
    description: 'Directory of the yarn.lock'
    required: true
    default: './'
outputs:
  diff:
    description: "Script output with the changed versions"
    value: ${{ steps.get-diff.outputs.diff }}
  outdated:
    description: "Script output with the outdated packages that are left after updating"
    value: ${{ steps.get-post-update-outdated.outputs.outdated }}
runs:
  using: "composite"
  steps:
    - run: yarn versions
      shell: bash
    - name: Install outdated tool
      shell: bash
      run: |
        yarn global add check-outdated
        echo "$(yarn global bin)" >> $GITHUB_PATH

    - run: yarn versions
      shell: bash
    - name: Install dependencies
      shell: bash
      run: yarn install --no-progress --cwd ${{ inputs.working-dir }}

    - name: Check pre update outdated
      shell: bash
      run: |
        set +e
        cd ${{ inputs.working-dir }}
        $( ! $(yarn global bin)/check-outdated --depth 1000 --ignore-dev-dependencies --columns name,current,latest,changes > ${{ runner.temp }}/pre-update )

    - name: Upgrade dependencies
      shell: bash
      run: yarn upgrade --no-progress --cwd ${{ inputs.working-dir }}

    - name: Check yarn outdated
      shell: bash
      id: get-post-update-outdated
      run: |
        set +e
        cd ${{ inputs.working-dir }}
        $( ! $(yarn global bin)/check-outdated --depth 1000 --ignore-dev-dependencies --columns name,current,latest,changes > ${{ runner.temp }}/post-update )
        echo "::set-output name=outdated::$(cat ${{ runner.temp }}/post-update)"

    - name: Make diff
      shell: bash
      id: get-diff
      # strip ansi colors and fix line breaks
      run: |
        pre=$(cat ${{ runner.temp }}/pre-update | sed '1,5d' | head -n -6 | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g" | sed -r "s/\\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g" )
        post=$(cat ${{ runner.temp }}/post-update | sed '1,5d' | head -n -6 | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g" | sed -r "s/\\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g" )
        diff=$(comm <(echo "$pre") <(echo "$post") -23)
        diff="${diff//'%'/'%25'}"
        diff="${diff//$'\n'/'%0A'}"
        diff="${diff//$'\r'/'%0D'}"
        echo "::set-output name=diff::$diff"
