name: 'Yarn upgrade'
description: 'Runs a yarn upgrade'
inputs:
  working-dir:
    description: 'Directory of the yarn.lock'
    required: true
    default: './'
  yarn-cache:
    description: 'Path to yarn cache'
    required: true
    default: /tmp/yarn-cache
  npm-version:
    description: 'Path to yarn cache'
    required: true
    default: /tmp/yarn-cache
outputs:
  diff:
    description: "Script output with the changed versions"
    value: ${{ steps.get-diff.outputs.diff }}
  outdated:
    description: "Script output with the outdated packages that are left after updating"
    value: ${{ steps.get-post-update-outdated.outputs.outdated }}
runs:
  using: "composite"
  steps:
    - name: Install outdated tool
      shell: bash
      run: |
        yarn global add check-outdated --preferred-cache-folder ${{ inputs.yarn-cache }}
        echo "$(yarn global bin)" >> $GITHUB_PATH

    - name: Install dependencies
      shell: bash
      run: yarn install --no-progress --preferred-cache-folder ${{ inputs.yarn-cache }} --cwd ${{ inputs.working-dir }}

    - name: Check pre update outdated
      shell: bash
      id: get-pre-update-outdated
      run: |
        set +e
        cd ${{ inputs.working-dir }}
        outdated=$( $(yarn global bin)/check-outdated --depth 1000 --ignore-dev-dependencies --columns name,current,latest,changes | sed '1,5d' | head -n -6 )
        echo $outdated
        echo "::set-output name=outdated::$outdated"

    - name: Upgrade dependencies
      shell: bash
      run: yarn upgrade --no-progress --preferred-cache-folder ${{ inputs.yarn-cache }} --cwd ${{ inputs.working-dir }}

    - name: Check yarn outdated
      shell: bash
      id: get-post-update-outdated
      run: |
        set +e
        cd ${{ inputs.working-dir }}
        outdated=$( $(yarn global bin)/check-outdated --depth 1000 --ignore-dev-dependencies --columns name,current,latest,changes | sed '1,5d' | head -n -6 )
        echo $outdated
        echo "::set-output name=outdated::$outdated"

  #        outdated="${outdated//$'\n'/'\n'}"
    - name: Make diff
      shell: bash
      id: get-diff
      run: |
        diff=$(comm <(echo "${{ steps.get-pre-update-outdated.outputs.outdated }}") <(echo "${{ steps.get-post-update-outdated.outputs.unformatted-outdated }}") -23)
        echo $diff
        diff="${diff//'%'/'%25'}"
        diff="${diff//$'\n'/'%0A'}"
        diff="${diff//$'\r'/'%0D'}"
        echo "::set-output name=diff::$diff"
