name: 'Yarn upgrade'
description: 'Runs a yarn upgrade'
inputs:
  working-dir:
    description: 'Directory of the yarn.lock'
    required: true
    default: './'
  yarn-cache:
    description: 'Path to yarn cache'
    required: true
    default: /tmp/yarn-cache
  npm-version:
    description: 'Path to yarn cache'
    required: true
    default: /tmp/yarn-cache
outputs:
  diff:
    description: "Script output with the changed versions"
    value: ${{ steps.get-diff.outputs.diff }}
  outdated:
    description: "Script output with the outdated packages that are left after updating"
    value: ${{ steps.get-post-update-outdated.outputs.outdated }}
runs:
  using: "composite"
  steps:
    - name: Install outdated tool
      shell: bash
      run: |
        yarn global add check-outdated --preferred-cache-folder ${{ inputs.yarn-cache }}
        echo "$(yarn global bin)" >> $GITHUB_PATH

    - name: Install dependencies
      shell: bash
      run: yarn install --no-progress --preferred-cache-folder ${{ inputs.yarn-cache }} --cwd ${{ inputs.working-dir }}

    - name: Check pre update outdated
      shell: bash
      run: |
        set +e
        cd ${{ inputs.working-dir }}
        $( ! $(yarn global bin)/check-outdated --depth 1000 --ignore-dev-dependencies --columns name,current,latest,changes > ${{ runner.temp }}/pre-update )

    - name: Upgrade dependencies
      shell: bash
      run: yarn upgrade --no-progress --preferred-cache-folder ${{ inputs.yarn-cache }} --cwd ${{ inputs.working-dir }}

    - name: Check yarn outdated
      shell: bash
      id: get-post-update-outdated
      run: |
        set +e
        cd ${{ inputs.working-dir }}
        $( ! $(yarn global bin)/check-outdated --depth 1000 --ignore-dev-dependencies --columns name,current,latest,changes > ${{ runner.temp }}/post-update )
        echo "::set-output name=outdated::$( cat ${{ runner.temp }}/post-update )"

    - name: Make diff
      shell: bash
      id: get-diff
      # strip ansi colors and fix line breaks
      run: |
        diff=$(grep -Fxv -f ${{ runner.temp }}/pre-update ${{ runner.temp }}/post-update -23)
        diff=$(echo "$diff" | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g" | sed -r "s/\\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g" )
        diff="${diff//'%'/'%25'}"
        diff="${diff//$'\r'/'%0D'}"
        echo "::set-output name=diff::$diff"
